server:
  port: 9002

spring:
  profiles:
    activate:
      on-profile: dev

  datasource:
    platform: mysql
    url: jdbc:mysql://jungmindb.c7pyd26tifkr.ap-northeast-2.rds.amazonaws.com:3306/Bunjang?autoReconnect=true # 변경해주세요
    username: master
    password: JjungminLee0964
    driver-class-name: com.mysql.cj.jdbc.Driver