server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://jungmindb.c7pyd26tifkr.ap-northeast-2.rds.amazonaws.com:3306/Bunjang?autoReconnect=true # 변경해주세요
    username: master
    password: JjungminLee0964
    driver-class-name: com.mysql.cj.jdbc.Driver